version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  server: 
    build: ./server
    volumes:
      - ./server:/src/app
    depends_on:
      - db
    ports:
      - 3030:3030
